// kramer-angular/src/shared/components/action-card/action-card.component.ts
import {Component} from '@angular/core';
import {StartIconComponent} from '../../icons/start-icon.component';

@Component({
  selector: 'app-action-card',
  standalone: true,
  imports: [
    StartIconComponent
  ],
  template: `
    <div class="w-[260px] h-[120px] border-2 rounded border-gray-300 m-[2px] flex flex-col">
      <div class="w-full h-[30px] pt-0.5 bg-kramer text-white uppercase text-center text-sm">
        Start quick test
      </div>
      <div class="flex items-center justify-center h-full">
        <app-start-icon></app-start-icon>
      </div>
    </div>
  `,
})
export class ActionCardComponent {
}

// kramer-react/src/components/action-card.jsx
import { PlayIcon } from "@heroicons/react/24/solid"

export function ActionCard() {
    return (
        <div className="w-[260px] h-[120px] border-2 rounded border-gray-300 m-[2px] flex flex-col">
            <div className="w-full h-[30px] pt-0.5 bg-kramer text-white uppercase text-center text-sm">
            TEST
            </div>
            <div className="flex items-center justify-center h-full">
                <PlayIcon className="h-20 w-20 text-kramer" />
            </div>
        </div>
    )
}
